---
apiVersion: v1
kind: Namespace
metadata:
  name: hariitns
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxwebapprc
  namespace: hariitns
spec:
  replicas: 3
  selector:
    app: nginxwebapp
  template:
    metadata:
      name: nginxwebapppod
      labels:
        app: nginxwebapp
    spec:
      containers:
      - name: nginxwebapp
        image: nginx
        ports:
        - containerPort: 80
---
#node-port service manifest
apiVersion: v1
kind: Service
metadata:
   name: nginxsvc
   namesapce: hariitns
spec:
    type: NodePort
    selector:
            app: nginxwebapp
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30222
