cat replicaset.yml 
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxwebapprc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxwebapp
  template:
    metadata:
      name: nginxwebapppod
      labels:
        app: nginxwebapp
    spec:
      containers:
      - name: nginxwebapp
        image: nginx
        ports:
        - containerPort: 80
---
#node-port service manifest
apiVersion: v1
kind: Service
metadata:
   name: nginxsvc
spec:
    type: NodePort
    selector:
            app: nginxwebapp
    ports:
    - port: 80
      targetPort: 80
ubuntu@ip-172-31-80-183:~$ kubectl delete all --all