---
apiVersion: v1
kind: Pod
metadata:
  name: mytomcat9
  labels:
    app: mytomcat9
spec:
  containers:
  - name: mytomcat9
    image: harikrishna857/mytomcat9
    ports:
    - containerPort: 80
...